Add AAL batch mode
GTNewHorizons/GigaGramFab pull request #32
Opened 2024-01-12 01:05 UTC by NotAPenguin0

This PR adds support for batch mode to the AAL. A few notes:

- Similarly to regular batch mode, the amount of batches to run is chosen so the time of each slice is at least 128 ticks. If the time per slice is already 128 ticks, this does nothing.
- Batch size is also controlled by how many recipes we can do with the amount of the first item we have. If we want to run 10 batches but only have enough starting items for 5, it will run 5 batches.
- If there are not enough fluids to run multiple batches, it will not batch at all and simply process one recipe at a time.
- If a slice cannot extract enough materials to do a full batch, it gets stuck (similarly to a regular AAL).
- Currently, this only works well with stocking input buses, see the comment I left on line 616. I don't think this should be a problem since you will never use input buses with more than one slot to automate an AAL.

Short demo video (not yet using adaptive batch sizes)

https://cdn.discordapp.com/attachments/181078474394566657/1195158820125679647/2024-01-12_00-56-03.mp4?ex=65b2f963&is=65a08463&hm=46e303eb5a61511b769e620a3835e182710cda46213236a29dd36f57df8645e1&

2024-01-12 05:51 UTC, Glease requested changes
besides the code problem I pointed out, I wonder if this change will actually make AAL slower...

2024-01-12 05:51 UTC, Glease commented on src/main/java/net/glease/ggfab/mte/MTE_AdvAssLine.java
> +    private int currentRecipeParallel = 1;
value is not persisted across chunk reload.

2024-01-12 05:51 UTC, Glease commented on src/main/java/net/glease/ggfab/mte/MTE_AdvAssLine.java
> +                        this.currentRecipeParallel = parallel;
this method is called in onRunningTick() as well (when first slice is idle). doing parallel here can have very bad outcome.

2024-01-12 09:01 UTC, NotAPenguin0 commented
> besides the code problem I pointed out, I wonder if this change will actually make AAL slower...

I don't think I added that much extra logic without compensating for it with longer recipe processing times, unless I'm missing something? Either way, I can probably try profiling this to check.

2024-01-12 11:10 UTC, Glease commented
slower as in less recipe done per second, not CPU usage

2024-01-12 12:46 UTC, NotAPenguin0 commented
Oh, yes this is true, you need to multiply patterns properly to make it actually use the pipeline parallel alongside batch mode parallel. Not sure how much of an issue this is.

2024-01-12 13:03 UTC, NotAPenguin0 commented
![image](https://github.com/GTNewHorizons/GigaGramFab/assets/26485755/db51b16c-86d6-4b09-b6b5-fb461df563c9)

My brain has stopped malfunctioning, it should come down to the same speed.

2024-01-13 01:06 UTC, Pelotrio submitted a review, later dismissed
Please also add being able to change batch mode using a wirecutter on the controller

2024-01-13 14:05 UTC, Pelotrio commented
@NotAPenguin0 Please make it consistent with other multiblocks where you also have to shift to change batch mode. Sorry that I was imprecise in my first review. For reference see processing array https://github.com/GTNewHorizons/GT5-Unofficial/blob/aaf21c6b36adcd2b8a2c7afaaa2bd9ae156d1475/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ProcessingArray.java#L357 or GT++ baseclass here https://github.com/GTNewHorizons/GTplusplus/blob/abfb399deb2763e014a20464c99c2b6c4c6d4e5e/src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GregtechMeta_MultiBlockBase.java#L1143

2024-01-14 14:54 UTC, NotAPenguin0 commented
I still want to make some changes to the batch mode formula to avoid the AAL being slower in some cases before this can be merged.

2024-01-25 01:47 UTC, gisi1037 commented
with batch mode could aals' be changed to have sub-one tick capability

2024-01-28 22:24 UTC, gisi1037 commented
Currently batch mode makes aals much slower. I did a test with 8192 mainframes using 16 aals on a subnet with and without batchmode, (newest nightly version https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/releases/tag/2.6.0-nightly-2024-01-26). it took 3x longer to finish the craft with the aals using batch mode because only 3 slices were ever used on each aal (2128 per slice * 16 aals * 4 slices = 8192. now this problem can be mitigated by using larger pattern sizes but it would mean needed massive patterns of 100k+ mainframes in this example and it would still be slower by a decent chunk. The current way batch size is determined which is calculated based on the assumption of a single aal per subnet to avoid slowdown, the issue here is if you add more aals on a subnet this breaks. My idea to fix this issue is to add a setting in the controller (preferably changeable by +1 or -1 using some kind of tool) to set the number of aals in the subnet. This way the batch mode can be scaled according to the number of aals in the subnet. another idea would be letting the aals communicate over an ae2 network somehow with stocking busses, but I'm not sure if this is at all possible and would likely be extremely dificult.

2024-02-21 13:15 UTC, Hikari1nVoid commented
>Currently, this only works well with stocking input buses,

Please add extra structure check for batchmode. The whole idea sounds way too dangerous in survival gameplay...

2024-02-21 13:15 UTC, Dream-Master commented
@NotAPenguin0

2024-02-21 15:15 UTC, NotAPenguin0 commented
I forgot about this, thanks for reminding me. I'll look into fixing the remaining bugs over the weekend

2024-02-23 18:06 UTC, Glease requested changes

2024-02-23 18:06 UTC, Glease commented
Feature summary (please confirm if my understanding matches yours):
1. batch mode up to 128 craft per batch
2. batch size is determined at each cold start. It is kept that way until it reaches a full stop. Even if say there are less than one batch but more than one craft worth of item in input.
3. no overclock after batching  

No.3 implies the machine cannot be faster than what it currently is, i.e. not a buff. however, due to reduction in cpu cycles consumption it might result in more stuff made per IRL hour. 

the code looks ok beyond one point that can be easily overlooked. I've left an review to explain it further. I don't fully agree with how batch mode is currently implemented, but I shall say it's better than not implementing batch mode at all.

---


 Sorry for being missing for so long. Life is hard.

2024-02-24 14:08 UTC, NotAPenguin0 commented
Seems like you've got it correct yeah. Besides the comment to add, there's still an issue with having multiple AAL connected to the same inputs. Currently, this causes the AALs to be slower than without batch mode, since they can't determine the optimal batch size anymore. I've asked a bit around and one possible solution seems to be to add a field in the controller to configure the number of AALs connected, but I'm 
- Not sure how to implement this
- If this is even the right/most convenient way to solve this

2024-02-24 15:43 UTC, Glease commented
We can just put that on backlog for now. Maybe the community can figure that out without code changes.

2024-02-27 02:09 UTC, Glease approved these changes

2024-02-27 15:09 UTC, merged